test:
  stage: test
  image: node:10.14.1
  script:
    - node --version
    - npm --version
    - npm install
    - npm run lint
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
    - npm run test
